### ISSUE TITLE
Number of items on carousel

### ISSUE THREAD

**Issue by castronet** [Kraymer/keyriban#1]
I would to give an idea about configuration.

Could you set some configuration file where the user could, for example, define how many letters appears on carousel.

**Comment by Kraymer** [comment]
Definitely possible.

As you're the first user to enter an issue on this project, could you tell me if the install process was straight enough, and if it works for you, generally speaking. You use keyriban for screencasts ?

**Comment by castronet** [comment]
I still doesn't used it but yes, I want to use it on my screencasts!

The install process of Keyriban is easy (and I'm not a Python lover) I had troubles installing the keylogger :)

Well, the install process for me was:

1. Clone the project
1. run python setup.py build && sudo python setup.py install 

(and in the middle, I had to install click, confuse and blessed (no documentation about it)

- sudo pip install click confuse blessed


Adding information on the ticket, I want to use keyriban on screencast but I need to:

- Customize the number of items displayed on the carousel.
- Find some way to increase the size of the text.
- Extra point: choose the colour of the text (and the 2nd colour, the shadowed text)


Regards,

**Comment by Kraymer** [comment]
> (and in the middle, I had to install click, confuse and blessed (no documentation about it)

You're right, i forgot to list requirements in *setup.py *!

Concerning size/colour of text I'll put an example of tmux configuration in *README.md* to achieve that as keyriban is expected to run in a dedicated tmux/screen panel anyway, it feels cleaner (and easier for me!) to let the multiplexer handle that part.

**Comment by Kraymer** [comment]
Here how make carousel use 5 letters instead of default 3 :
    
    $ more ~/.config/keyriban/config.yaml
    format_closing: yes
    chars_skip: 8
    ring:
        length: 5

*(consider just the two last lines)*
